version: 2
updates:
  # Update Gradle dependencies located in the root project directory, including the Gradle Wrapper
  - package-ecosystem: "gradle"
    directory: "/" # Root directory of the project
    schedule:
      interval: "weekly" # Dependabot will check for updates weekly
    open-pull-requests-limit: 10
